# Generated by Django 4.2 on 2026-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_entrada', models.TimeField()),
                ('hora_fin_entrada', models.TimeField()),
                ('hora_inicio_salida', models.TimeField()),
                ('hora_fin_salida', models.TimeField()),
                ('max_intentos', models.IntegerField(default=5)),
                ('max_intentos_faciales', models.IntegerField(default=5)),
                ('umbral_similitud', models.FloatField(default=0.6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
