# Generated by Django 4.2 on 2026-03-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='ConfiguracionSistema',
        ),
    ]
