# Generated by Django 4.2 on 2026-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_rename_configuracion_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='control_ip_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ip_autorizada',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
