# Generated by Django 4.2 on 2026-03-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracionsistema_control_ip_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ip_autorizada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
