# Generated by Django 4.2 on 2026-03-13 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_debe_cambiar_password'),
        ('configuracion', '0004_alter_configuracionsistema_ip_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_modificadas', to='usuarios.usuario'),
        ),
    ]
