# Generated by Django 4.2 on 2026-03-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_configuracionsistema_ultima_modificacion_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionsistema',
            old_name='ultima_modificacion_por',
            new_name='ultima_modificacion_por_id',
        ),
    ]
