# Generated by Django 4.2 on 2026-03-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('estado', models.CharField(blank=True, choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza')], max_length=10, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=150, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcaciones', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'db_table': 'marcaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
