# Generated by Django 4.2 on 2026-03-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='trabajadores',
        ),
    ]
