# Generated by Django 4.2 on 2026-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_alter_trabajador_options_alter_trabajador_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
